// {c} = character name
// {g} = game name
// {r} = other

const phrase_list = [
	"{c} is a fascist",
	"{c} is racist",
	"I don't get why people like {c}'s character, they're literally just a one note personality",
	"{c} is only liked because of their tits",
	"{c} is only liked because of their thighs",
	"{c}'s character is just a worse version of {c}",
	"{c}'s character is just a better version of {c}",
	"{c} is a bottom",
	"{c} is a top",
	"{c} ruined Fire Emblem",
	"Maeda ruined {c}",
	"{c} would have been better if they joined earlier",
	"{c} is the best character in the franchise",
	"{c} is the worst character in the franchise",
	"{c} is the best character in {g}",
	"{c} is the worst character in {g}",
	"{c} x {c} is the best ship",
	"{c} x {c} is the worst ship",
	"Heroes ruined {c}",
	"I like the {c} archetype",
	"I hate the {c} archetype",
	"{c} is hypocritical",
	"{c} is an asshole",
	"{c} being shipped with {c} is actually terrible because it promotes {r}",
	"Kaga did {r} first",
	"{c} is underrated", 
	"{c} is overrated",
	"{r} was done better in Tear Ring Saga",
	"{c}'s character is problematic because it promotes {r}",
	"{g} has major issues with {r}",
	"{c} is a war criminal",
	"BSFE is better than {g}",
	"{c} deserves to die",
	"{c}'s character provides a deep analysis on {r}",
	"{c} is the worst part of {g}",
	"{c} did nothing wrong",
	"{c} stans are the worst",
	"{c} fucks",
	"{c} hates {r}",
	"{r} ruined {g}",
	"{c} needs a Summer alt in Heroes",
	"The perfect Fire Emblem Warriors roster: {c}, {c}, {c}, {c}, and {c}",
	"IS needs to add a new alt for {c} in Heroes",
	"I wish {g} had a DLC with a new {c} costume",
	"Where is the {g} remake? I want them to buff {c}!",
	"{c} ended {r}",
	"{c} jokes are not funny",
	"{g} is the Dark Souls of Fire Emblem",
	"{c} is the hottest Fire Emblem character"
]